### ISSUE TITLE
A problem occurred evaluating project ':nordic_nrf_mesh'.

### ISSUE THREAD

**Issue by Hung6129** [OZEO-DOOZ/nrf_mesh_plugin#248]
I have a problem that when I run the application on flutter, it gives me this error in the terminal

what i want to do is to scan the nearest bluetooth device, get the uuid and node from that device then control it example: control light

here is the error in the terminal:
FAILURE: Build failed with an exception.
Where:
Build file 'C:%user%\flutter.pub-cache\hosted\pub.dartlang.org\nordic_nrf_mesh-0.12.0\android\build.gradle' line: 44
What went wrong:
A problem occurred evaluating project ':nordic_nrf_mesh'.
Project with path ':mesh' could not be found in project ':nordic_nrf_mesh'.

Try:
Run with --stacktrace option to get the stack trace.
Run with --info or --debug option to get more log output.
Run with --scan to get full insights.

check my stackoverflow for detail 
https://stackoverflow.com/questions/73958108/a-problem-occurred-evaluating-project-nordic-nrf-mesh

**Comment by Hung6129** [comment]
So, actually right now i just need to do a function to scan around and detect the available device with bluetooth
I found  nrf_mesh_plugin has all function that i need (scanForUnprovisionedNodes, provisionedNodesInRange,...)
In the future, i will use the uuid and id, send it to the server 
I don't know why i bumped to that error(A problem occurred evaluating project ':nordic_nrf_mesh'.)
Is that error a rare error?
By the way thanks for keep update and thanks you for the plugin, Much love<3

**Comment by R0m4in-dooz** [comment]
Hello @Hung6129 !

Ok 🤔 so, as much as I love to see that our plugin as users, I think I can't advise you to use it if you only need the scanning feature !

Fork the pkg and extract ´lib/ble/ble_scanner.dart´ to your project as standalone file should be enough if I don't misunderstand your use case

**Comment by R0m4in-dooz** [comment]
For the error you have, it's just that the plugin's readme is missing installation steps 😅

**Comment by R0m4in-dooz** [comment]
I have documented how you should install in a new issue :
