### ISSUE TITLE
Missing installation steps in README

### ISSUE THREAD

**Issue by R0m4in-dooz** [OZEO-DOOZ/nrf_mesh_plugin#249]
We don't document how to install, which leads to confused users.
The steps should be :
- add to pubspec
- flutter pub get
- go to cached folder (nrf_mesh_plugin_<commit_hash> or smth)
- git submodule update --init
- go to android/settings.gradle
- copy script found in the end of plugin's example/android/settings.gradle 

Then it's rdy for android compilation. For iOS there is another step

**Comment by Hung6129** [comment]
@R0m4in-dooz 
Awesome work man
It works!!!!
Now i can use all the functions
Thanks you so much

**Comment by redclouddrailan** [comment]
Hello, when I go to cached folder, in windows which for me is this link:  ~/AppData/Local/Pub/Cache/hosted/pub.dev/nordic_nrf_mesh-0.13.0

I can't run the git submodule update --init, it says "fatal: not a git repository (or any of the parent directories): .git"

**Comment by SyedKaz00** [comment]
> Hello, when I go to cached folder, in windows which for me is this link: ~/AppData/Local/Pub/Cache/hosted/pub.dev/nordic_nrf_mesh-0.13.0
> 
> I can't run the git submodule update --init, it says "fatal: not a git repository (or any of the parent directories): .git"

Same

**Comment by vibhu792** [comment]
i m facing same problem in nordic_nrf_mesh how to resolve ?????
