### ISSUE TITLE
Mesh network database import fails

### ISSUE THREAD

**Issue by codezork** [OZEO-DOOZ/nrf_mesh_plugin#250]
A json file exported from https://github.com/NordicSemiconductor/Android-nRF-Mesh-Library cannot be imported. Crashes with: ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MeshNetworkEventError(error: Invalid Mesh Provisioning/Configuration Database JSON file, unsupported ID).
The original app by Nordic Semi can import its own export.

**Comment by R0m4in-dooz** [comment]
Hello @codezork,
Thanks for the report !

Nordic's app may have a newer SDK version than this plugin. See #246.

Unfortunately at the moment I can't debug it but I suspect this is the reason why your export cannot be imported : they may have change something since our latest upgrade. Could you check this idea ?

**Comment by R0m4in-dooz** [comment]
Also, if my above comment doesn't help it would be much appreciated if you could upload here a json file that makes the plugin throwing this error 🙏

**Comment by codezork** [comment]
This is the JSON from Nordic:

**Comment by codezork** [comment]
The readme.mo from nordic says: The mesh network configuration (JSON schema) is compatible with
- **Mesh Configuration Database Profile 1.0**. So nothing should have been changed. Are you completely in nordic's code while importing?

**Comment by R0m4in-dooz** [comment]
You are right there should not be any changes because of the spec.
Yes this plugin is only a wrapper on the Nordic SDK 👍 so the json is not altered before "entering" their code.

Thanks for the json, I will try to find time to debug this this week as I understand this is a blocker for you.

**Comment by codezork** [comment]
Excellent! Thank you

**Comment by Nanodash** [comment]
Hello @codezork,
I began to update the plugin, I will do some non-regression tests and will then look at your issue. Sorry for the delay !

**Comment by Nanodash** [comment]
Hi @codezork , I've found the issue. It's indeed a version issue. It's seems that schema id has changed from `http://www.bluetooth.com/specifications/assigned-numbers/mesh-profile/cdb-schema.json#` to yours : "https://www.bluetooth.com/specifications/specs/mesh-cdb-1-0-1-schema.json#", and our version of Nordic SDK is throwing for this

**Comment by Nanodash** [comment]
the fix is pretty straight forward : update Nordic dependencies
