### ISSUE TITLE
How to set device name to node name in json file

### ISSUE THREAD

**Issue by Hung6129** [OZEO-DOOZ/nrf_mesh_plugin#253]
When i provisioned a node then i export json file 
In the node list the node name is default  "My node " like is always 
So i want to set the node name in the json file according to the device name that i provisioning

 from this
![image](https://user-images.githubusercontent.com/73824851/196140416-11cb2da2-899f-41a7-bf4f-fbeab36a1acf.png)

to this

![image](https://user-images.githubusercontent.com/73824851/196140236-caaa3ba6-9ef2-46d8-872d-0f3d044fe44e.png)

thanks

**Comment by Hung6129** [comment]
Am i doing wrong some where or i have to change something on the native code? Pls help
In the android app https://github.com/NordicSemiconductor/Android-nRF-Mesh-Library 
when i use it to export json file it still keep my device name also in ios app

**Comment by R0m4in-dooz** [comment]
Hi @Hung6129,

Nothing wrong here, we just don't expose the api and we don't use device name when creating node object !

This looks like a feature request 👍

**Comment by Hung6129** [comment]
hope this feature will appear soon

**Comment by Hung6129** [comment]
i don't identify it by using device name, i use uuid
i just need to show the device name on the json file just like the android app when i export it 

bc i will send that json file to the server and they want to know the device name in the list node :(

can you give me some solution to get the device name instead of the default name "My node"

i see that in the DiscoveredDevice models has the name
Now how can i add it into the ProvisionedNode 

Thanks

**Comment by R0m4in-dooz** [comment]
Hello @Hung6129,

If you want to try and implement it, I think it's more on the native code that you have to change something. The provisioning process may look complex, so you better begin by just exposing Node.setName from Nordic API

**Comment by him1010** [comment]
Hello 
  I am new to app development and I want to save the new provisioned device with its original name or provide a name for it. If possible can you help me with this.

Thanks

**Comment by Hung6129** [comment]
![image](https://user-images.githubusercontent.com/73824851/204419062-d03d4c69-42d6-4e39-bab7-e757859e3920.png)

hello @him1010 
Well for now i added that line to set the provisioned nodeName after the provisioning step this done
It works and show the name of the device instead of My Node
@R0m4in-dooz sir, a feature request ??

**Comment by R0m4in-dooz** [comment]
Hello !

Ah yes this line is ok ✅ 

Feel free to open a PR 👍

_It could be great to expose the name setter in mesh mngr in case you want to change it later (user customization for instance)_

**Comment by him1010** [comment]
Hello @Hung6129 
   Thanks for the suggestion. It worked.
   @R0m4in-dooz how can I expose the name setter in mesh manager and use it, if you could give an example that would be really helpful.

Thanks

**Comment by R0m4in-dooz** [comment]
Hello @him1010,

Actually I found that it is already exposed, see models file for mesh nodes, there is ProvisionedMeshNodes which defines an async setter : https://github.com/OZEO-DOOZ/nrf_mesh_plugin/blob/master/lib/src/models/mesh_node/provisioned_mesh_node.dart

**Comment by R0m4in-dooz** [comment]
So to do it after provisioning you can write : 
```dart
// with an instance that implements IMeshNetwork
IMeshNetwork _meshNetwork;
// and target node´s unicast
int unicast;

final node = await _meshNetwork.getNode(unicast);

await node.setName('my awesome mesh node');

```

**Comment by R0m4in-dooz** [comment]
This issue seems resolved. If you think it's not the case, feel free to re-open it 😊
